name: Hello CI (Self-Hosted Runner)

on:
  workflow_dispatch:

jobs:
  hello-self-hosted:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Hello message
        run: echo "Hello, CI with GitHub Actions! (self-hosted)"

      - name: Run tests
        shell: powershell
        run: py -m unittest -v

